<?php

namespace app\index\controller;

use think\Request;

class Ads extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //config('template', ['layout_on' => false]);
    }

    public function index()
    {
        $this->title("全部地摊广告");
        return $this->fetch();
    }

    public function ad()
    {
        //config('template', ['layout_on' => false]);
        $this->title('地摊项目网 - 精选地摊创业项目');
        $ads_num = mt_rand(0, 1);
        if ($ads_num) {
            return $this->fetch('ad3');
        }
        return $this->fetch('ad2');
    }

    public function ad1()
    {
        $this->title("海澜之家剪标羽绒服");
        return $this->fetch();
    }

    public function ad2()
    {
        $this->title("棉里爱");
        return $this->fetch();
    }

    public function ad3()
    {
        $this->title("韩国超市中国店倒闭下架精品筷");
        return $this->fetch();
    }
}
