<?php

namespace app\index\controller;

use think\Request;

class Ads extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //config('template', ['layout_on' => false]);
    }

    public function ad()
    {
        //config('template', ['layout_on' => false]);
        $this->title('地摊项目网 - 精选地摊创业项目');
        $ads_num = mt_rand(0, 1);
        if ($ads_num) {
            return $this->fetch('ad3');
        }
        return $this->fetch('ad2');
    }
}
